### ISSUE TITLE
Make page responsive

### ISSUE THREAD

**Issue by rwishavg** [rwishavg/indiaVScovid#1]
The page is not responsive. Certain elements may need formatting. 

Please create your own branch when making a contribution. 
DO NOT PUSH INTO MAIN BRANCH. 

Skills Required : HTML, CSS

In case of doubts or if in need of help, feel free to ask below.

**Comment by Blazing-Mike** [comment]
Can you assign me to issue?

**Comment by Blazing-Mike** [comment]
Do I need to install all those packages before I can contribute to the project.

**Comment by rwishavg** [comment]
You do not need to install any package. Please just work on the public directory. You only need to work on the html, css and maybe the js files. Let me know if you understand the problem well. I am assigning the issue to you.

**Comment by Blazing-Mike** [comment]
Understood. I have forked the repo already.
